language: cpp
compiler: clang
git:
- submodules: false
before_install:
- sed -i 's/git@github.com:/git:\/\/github.com\//' .gitmodules
- git submodule update --init --recursive
install:
- DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
- mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
- travis_retry wget --no-check-certificate https://cmake.org/files/v3.15/cmake-3.15.4-Linux-x86_64.tar.gz
- tar -xvf cmake-3.15.4-Linux-x86_64.tar.gz > /dev/null
- mv cmake-3.15.4-Linux-x86_64 cmake-install
- PATH=${DEPS_DIR}/cmake-install:${DEPS_DIR}/cmake-install/bin:$PATH
- cd ${TRAVIS_BUILD_DIR}
before_script:
- echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -qq
- sudo apt-get install doxygen
script:
- mkdir build
- cd build
- cmake ..
- cmake --build .
- cmake --build . --target package
- doxygen doxygen.conf
deploy:
    provider: script
    skip_cleanup: true
    script:
    - curl -T print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -utantskii:$BINTRAY_API_KEY "https://api.bintray.com/content/myorguniqueid/otus/print_ip/$TRAVIS_BUILD_NUMBER/print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    local_dir: "doc/html"
    on:
      branch: master
